name: "Hello Actions"

description: "Greet someone"

author: "test@some.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "HHH"
  
  runs:
    using: "docker"
    image: "Dockerfile"
    
  branding:
    icon: "mic"
    color: "purple"
