name: A test workflow
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-linux
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "some name"
